PREFIX x2rm: <http://ids.unimaas.nl/xml2rdf/model#>
PREFIX x2rd: <http://ids.unimaas.nl/xml2rdf/data/>
PREFIX d2s: <https://w3id.org/data2services/vocab/>
PREFIX ido: <http://identifiers.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bl: <https://w3id.org/biolink/vocab/>
PREFIX drugbank_vocabulary: <http://bio2rdf.org/drugbank_vocabulary:>
PREFIX bio2rdf_vocabulary: <http://bio2rdf.org/bio2rdf_vocabulary:> 

INSERT 
{ 
    GRAPH <https://w3id.org/data2services/graph/drugbank> {  

	?uri	a drugbank_vocabulary:Resource;
		rdf:type drugbank_vocabulary:Link;
		dc:identifier ?dcId;
		rdfs:label ?label;
		dc:title ?title;
		bio2rdf_vocabulary:namespace "drugbank";
		bio2rdf_vocabulary:identifier ?linkRefIdValue;
		bio2rdf_vocabulary:uri ?uri;

		drugbank_vocabulary:title ?linkTitleValue;
		drugbank_vocabulary:url ?linkUrlUri;
    }
}
WHERE {
  
  GRAPH  <https://w3id.org/data2services/graph/xml2rdf> {

	?link a ?linkType.

	OPTIONAL{
		?link x2rm:hasChild ?linkRefId.
		?linkRefId a ?linkRefIdType.
		?linkRefId x2rm:hasValue ?linkRefIdValue.
	} OPTIONAL{
		?link x2rm:hasChild ?linkTitle.
		?linkTitle a ?linkTitleType.
		?linkTitle x2rm:hasValue ?linkTitleValue.
	} OPTIONAL{
		?link x2rm:hasChild ?linkUrl.
		?linkUrl a ?linkUrlType.
		?linkUrl x2rm:hasValue ?linkUrlValue.
	} # Target Ref Articles features
  
	VALUES( ?linkType ?linkRefIdType ?linkTitleType ?linkUrlType) {

		(x2rm:drugbank.drug.general-references.links.link x2rm:drugbank.drug.general-references.links.link.ref-id x2rm:drugbank.drug.general-references.links.link.title x2rm:drugbank.drug.general-references.links.link.url)

		(x2rm:drugbank.drug.targets.target.references.links.link x2rm:drugbank.drug.targets.target.references.links.link.ref-id x2rm:drugbank.drug.targets.target.references.links.link.title x2rm:drugbank.drug.targets.target.references.links.link.url)

		(x2rm:drugbank.drug.enzymes.enzyme.references.links.link x2rm:drugbank.drug.enzymes.enzyme.references.links.link.ref-id x2rm:drugbank.drug.enzymes.enzyme.references.links.link.title x2rm:drugbank.drug.enzymes.enzyme.references.links.link.url)

		(x2rm:drugbank.drug.carriers.carrier.references.links.link x2rm:drugbank.drug.carriers.carrier.references.links.link.ref-id x2rm:drugbank.drug.carriers.carrier.references.links.link.title x2rm:drugbank.drug.carriers.carrier.references.links.link.url)

		(x2rm:drugbank.drug.transporters.transporter.references.links.link x2rm:drugbank.drug.transporters.transporter.references.links.link.ref-id x2rm:drugbank.drug.transporters.transporter.references.links.link.title x2rm:drugbank.drug.transporters.transporter.references.links.link.url)

	} # VALUES
	BIND ( iri(concat("http:", ?linkUrlValue)) AS ?linkUrlUri )

	BIND ( concat("drugbank:", ?linkRefIdValue) AS ?dcId )
	BIND ( concat("Reference Link ", ?linkRefIdValue) AS ?title)
	BIND ( concat(?title, " [drugbank:", ?linkRefIdValue, "] ") AS ?label )
	BIND ( iri(concat("http://bio2rdf.org/drugbank:", ?linkRefIdValue)) AS ?uri )	
  } # graph
  
} # where
