PREFIX x2rm: <http://ids.unimaas.nl/xml2rdf/model#>
PREFIX x2rd: <http://ids.unimaas.nl/xml2rdf/data/>
PREFIX d2s: <https://w3id.org/data2services/vocab/>
PREFIX ido: <http://identifiers.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bl: <https://w3id.org/biolink/vocab/>
PREFIX drugbank_vocabulary: <http://bio2rdf.org/drugbank_vocabulary:>
PREFIX bio2rdf_vocabulary: <http://bio2rdf.org/bio2rdf_vocabulary:> 

INSERT 
{ 
    GRAPH <https://w3id.org/data2services/graph/drugbank> {  

	?uri	a drugbank_vocabulary:Resource;
		rdf:type drugbank_vocabulary:Patent;
		dc:identifier ?dcId;
		rdfs:label ?label;
		dc:title ?title;
		bio2rdf_vocabulary:namespace "uspto";
		bio2rdf_vocabulary:identifier ?itemId;
		bio2rdf_vocabulary:uri ?uri; 

		drugbank_vocabulary:country ?countryUri;
		drugbank_vocabulary:approved ?patentApproved;
 		drugbank_vocabulary:expires ?patentExpires;
 		drugbank_vocabulary:pediatric-extension ?patentPediatricExtension; 
    }
}
WHERE {
  
  GRAPH <https://w3id.org/data2services/graph/xml2rdf> {

	?patent a x2rm:drugbank.drug.patents.patent; 

	OPTIONAL{
		?patent x2rm:hasChild [
		    a x2rm:drugbank.drug.patents.patent.number; 
		    x2rm:hasValue ?patentNumber
	    	];
	} OPTIONAL{
		?patent x2rm:hasChild [
		    a x2rm:drugbank.drug.patents.patent.country; 
		    x2rm:hasValue ?patentCountry
	    	];
	} OPTIONAL{
		?patent x2rm:hasChild [
		    a x2rm:drugbank.drug.patents.patent.approved; 
		    x2rm:hasValue ?patentApproved
	    	];
	} OPTIONAL{
		?patent x2rm:hasChild [
		    a x2rm:drugbank.drug.patents.patent.expires; 
		    x2rm:hasValue ?patentExpires
	    	];
	} OPTIONAL{
		?patent x2rm:hasChild [
		    a x2rm:drugbank.drug.patents.patent.pediatric-extension; 
		    x2rm:hasValue ?patentPediatricExtension
	    	];
	} # patents features 

	BIND ( SHA1(STR(?patentCountry)) AS ?countryId)
	BIND ( iri(concat("http://bio2rdf.org/drugbank_resource:", ?countryId)) AS ?countryUri )

	BIND ( concat(?patentCountry, " patent ", ?patentNumber) AS ?title)
	BIND ( concat("uspto:", ?patentNumber) AS ?dcId )
	BIND ( concat(?title, " [uspto:", ?patentNumber, "] ") AS ?label )
	BIND ( iri(concat("http://bio2rdf.org/uspto:", ?patentNumber)) AS ?uri )

  } # graph
  
} # where
