working_directory: /media/apc/DATA1/Maastricht/bio2rdf-github

dataset: drugbank

download_username: vincent.emonet@maastrichtuniversity.nl
download_password: maasitest12
# R2RML params
input_data_jdbc: "jdbc:drill:drillbit=drill:31010"
sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/autor2rml/drugbank"
sparql_base_uri: "https://w3id.org/data2services/"
#autor2rml_column_header: "test1,test2,test3,test5"

sparql_input_graph_uri: https://w3id.org/data2services/graph/drugbank

# RdfUpload params
sparql_triplestore_url: http://graphdb:7200
sparql_triplestore_repository: drugbank

sparql_transform_queries_path: /data/mapping/drugbank/transform
sparql_insert_metadata_path: /data/mapping/drugbank/metadata



