working_directory: /media/apc/DATA1/Maastricht/bio2rdf-github

dataset: goa

# R2RML params
input_data_jdbc: "jdbc:drill:drillbit=drill:31010"
sparql_tmp_graph_uri: "https://w3id.org/data2services/graph/autor2rml/goa"
sparql_base_uri: "https://w3id.org/data2services/"
#autor2rml_column_header: "test1,test2,test3,test5"

# RdfUpload params
sparql_triplestore_url: http://virtuoso:8890/sparql

triple_store_password: dba
triple_store_username: dba

sparql_input_graph_uri: https://w3id.org/data2services/graph/goa

sparql_transform_queries_path: /data/mapping/goa/transform
sparql_insert_metadata_path: /data/mapping/goa/metadata

# Split params
split_property_0: https://w3id.org/data2services/model/Db_obj_synonym
split_class_0: https://w3id.org/data2services/data/input/goa/goa_human.tsv
split_delimiter_0: "|"

split_property_1: https://w3id.org/data2services/model/Db_ref
split_class_1: https://w3id.org/data2services/data/input/goa/goa_human.tsv
split_delimiter_1: '|'
