PREFIX rr: <http://www.w3.org/ns/r2rml#> 
PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX dbo: <http://dbpedia.org/ontology/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rml: <http://semweb.mmlab.be/ns/rml#> 
PREFIX ql: <http://semweb.mmlab.be/ns/ql#> 
PREFIX d2rq: <http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#> 
PREFIX drugbank_vocabulary: <http://bio2rdf.org/drugbank_vocabulary:> 
PREFIX pharmgkb_vocabulary: <http://bio2rdf.org/pharmgkb_vocabulary:> 
PREFIX clinicaltrials_vocabulary: <http://bio2rdf.org/clinicaltrials_vocabulary:> 
PREFIX go_vocabulary: <http://bio2rdf.org/go_vocabulary:> 
PREFIX goa_vocabulary: <http://bio2rdf.org/goa_vocabulary:> 
PREFIX bio2rdf_vocabulary: <http://bio2rdf.org/bio2rdf_vocabulary:> 
PREFIX d2sgeneric: <https://w3id.org/data2services/model/>


INSERT
{
	GRAPH <https://w3id.org/data2services/graph/pharmgkb>{
		
		?uri	a pharmgkb_vocabulary:Resource;
			rdf:type pharmgkb_vocabulary:Phenotype;
			dc:identifier ?phenotypeId;
			rdfs:label ?label;
			dc:title ?name;
			bio2rdf_vocabulary:namespace "pharmgkb";
			bio2rdf_vocabulary:identifier ?accessionID;
			bio2rdf_vocabulary:uri ?uri;
			pharmgkb_vocabulary:alternative-name ?alternate_name;
			pharmgkb_vocabulary:x-ref ?cross_references;
			pharmgkb_vocabulary:x-ref ?external_vocab;
	}
}
WHERE {
    GRAPH <https://w3id.org/data2services/graph/autor2rml> {
		
		?s rdf:type <https://w3id.org/data2services/data/input/pharmgkb/phenotypes/phenotypes.tsv>.
		?s d2sgeneric:PharmgkbAccessionId ?accessionID .
		
		BIND ( iri(concat("pharmagkb:", ?accessionID) ) AS ?phenotypeId )
		
		OPTIONAL { 
         	 ?s d2sgeneric:Name ?name .
		 BIND ( concat(?name, " [pharmgkb:", ?accessionID, "] ") AS ?label )
			
		} OPTIONAL {
         	 ?s d2sgeneric:AlternateNames ?alternate_name .

		} OPTIONAL {
		 ?s d2sgeneric:CrossReferences ?cross_references .

		} OPTIONAL {
		 ?s d2sgeneric:ExternalVocabulary ?external_vocab .
		
		}
			
		BIND ( iri(concat("http://bio2rdf.org/pharmgkb:", ?accessionID)) AS ?uri )
		
	}
}	
