PREFIX rr: <http://www.w3.org/ns/r2rml#> 
PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX dbo: <http://dbpedia.org/ontology/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rml: <http://semweb.mmlab.be/ns/rml#> 
PREFIX ql: <http://semweb.mmlab.be/ns/ql#> 
PREFIX d2rq: <http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#> 
PREFIX drugbank_vocabulary: <http://bio2rdf.org/drugbank_vocabulary:> 
PREFIX hgnc_vocabulary: <http://bio2rdf.org/hgnc_vocabulary:> 
PREFIX clinicaltrials_vocabulary: <http://bio2rdf.org/clinicaltrials_vocabulary:> 
PREFIX go_vocabulary: <http://bio2rdf.org/go_vocabulary:> 
PREFIX goa_vocabulary: <http://bio2rdf.org/goa_vocabulary:> 
PREFIX bio2rdf_vocabulary: <http://bio2rdf.org/bio2rdf_vocabulary:> 
PREFIX d2sgeneric: <https://w3id.org/data2services/model/>

INSERT
{
	GRAPH <https://w3id.org/data2services/graph/hgnc>{
		
		?uri	a hgnc_vocabulary:Resource;
			rdf:type hgnc_vocabulary:Gene-Symbol;
			dc:identifier ?geneID;
			rdfs:label ?label;
			dc:title ?name;
			bio2rdf_vocabulary:namespace "hgnc";
			bio2rdf_vocabulary:identifier ?accessionID;
			bio2rdf_vocabulary:uri ?uri;
			hgnc_vocabulary:approved-symbol ?ApprovedSymbol;
			hgnc_vocabulary:approved-name ?ApprovedName;
			hgnc_vocabulary:status ?Status;
			hgnc_vocabulary:locus-type ?LocusType;
			hgnc_vocabulary:locus-group ?LocusGroup;
			hgnc_vocabulary:previous-symbol ?PreviousSymbols;
			hgnc_vocabulary:previous-name ?PreviousNames;
			hgnc_vocabulary:synonym ?Synonyms;
			hgnc_vocabulary:name-synonym ?NameSynonyms;
			hgnc_vocabulary:chromosome ?Chromosome;
			hgnc_vocabulary:date-approved ?DateApproved;
			hgnc_vocabulary:date-modified ?DateModified;
			hgnc_vocabulary:date-symbol-changed ?DateSymbolChanged;
			hgnc_vocabulary:date-name-changed ?DateNameChanged;
			hgnc_vocabulary:x-ec ?EnzymeIds;
			hgnc_vocabulary:x-ncbigene ?EntrezGeneId;
			hgnc_vocabulary:x-ensembl ?EnsemblGeneId;
			hgnc_vocabulary:x-mgi ?mgi_main;
			hgnc_vocabulary:x-pubmed ?PubmedIds;
			hgnc_vocabulary:x-refseq ?RefseqIds;
			hgnc_vocabulary:gene-family-tag ?GeneFamilyTag;
			hgnc_vocabulary:gene-family-description ?GeneFamilyDescription;
			hgnc_vocabulary:x-ccds ?CcdsIds;
			hgnc_vocabulary:x-vega ?VegaIds;
			hgnc_vocabulary:x-ncbigene ?EntrezGeneIdSuppliedByNcbi;
			hgnc_vocabulary:x-omim ?OmimIdSuppliedByNcbi;
			hgnc_vocabulary:x-refseq ?RefseqSuppliedByNcbi;
			hgnc_vocabulary:x-uniprot ?UniprotIdSuppliedByUniprot;
			hgnc_vocabulary:x-ensembl ?EnsemblIdSuppliedByEnsembl;
			hgnc_vocabulary:x-vega ?VegaIdSuppliedByVega;
			hgnc_vocabulary:x-ucsc ?UcscIdSuppliedByUcsc;
			hgnc_vocabulary:x-mgi ?mgi;
			hgnc_vocabulary:x-rgd ?rgd;
			hgnc_vocabulary:x-rnacentral ?RnacentralIdsSuppliedByRnacentral;
			hgnc_vocabulary:x-lnci ?LncipediaSymbolSuppliedByLncipedia.			
	}
}
WHERE {
    GRAPH <https://w3id.org/data2services/graph/autor2rml/hgnc> {

		?s rdf:type <https://w3id.org/data2services/data/input/hgnc/hgnc_complete_set.tsv>.

		?s d2sgeneric:Hgnc_id ?fullID .
		BIND ( SUBSTR(?fullID,6) AS ?accessionID )
		
		BIND ( iri(concat("hgnc:", ?accessionID) ) AS ?geneID )
		
		OPTIONAL { 
         	 ?s d2sgeneric:Symbol ?name .
		 BIND ( concat("Gene Symbol for ",?name, " [hgnc:", ?accessionID, "] ") AS ?label )
			
		} OPTIONAL {
         	 ?s d2sgeneric:Symbol ?ApprovedSymbol .	
		} OPTIONAL {
         	 ?s d2sgeneric:Name ?ApprovedName .	
		} OPTIONAL {
         	 ?s d2sgeneric:Status ?Status .	
		} OPTIONAL {
         	 ?s d2sgeneric:Locus_type ?LocusType .	
		} OPTIONAL {
         	 ?s d2sgeneric:Locus_group ?LocusGroup .	
		} OPTIONAL {
         	 ?s d2sgeneric:Prev_symbol ?PreviousSymbols .	
		} OPTIONAL {
         	 ?s d2sgeneric:Prev_name ?PreviousNames .	
		} OPTIONAL {
         	 ?s d2sgeneric:Alias_symbol ?Synonyms .	
		} OPTIONAL {
         	 ?s d2sgeneric:Alias_name ?NameSynonyms .	
		} OPTIONAL {
         	 ?s d2sgeneric:Location ?Chromosome .	
		} OPTIONAL {
         	 ?s d2sgeneric:Date_approved_reserved ?DateApproved .	
		} OPTIONAL {
         	 ?s d2sgeneric:Date_modified ?DateModified .	
		} OPTIONAL {
         	 ?s d2sgeneric:Date_symbol_changed ?DateSymbolChanged .	
		} OPTIONAL {
         	 ?s d2sgeneric:Date_name_changed ?DateNameChanged .	
		} OPTIONAL {
         	 ?s d2sgeneric:Enzyme_id ?EnzymeIdsR .	
		 BIND ( iri(concat("http://bio2rdf.org/ec:", ?EnzymeIdsR)) AS ?EnzymeIds )
		} OPTIONAL {
         	 ?s d2sgeneric:Entrez_id ?EntrezGeneIdR .	
		 BIND ( iri(concat("http://bio2rdf.org/ncbigene:", ?EntrezGeneIdR)) AS ?EntrezGeneId )
		} OPTIONAL {
         	 ?s d2sgeneric:Ensembl_gene_id ?EnsemblGeneIdR .
		 BIND ( iri(concat("http://bio2rdf.org/ensembl:", ?EnsemblGeneIdR)) AS ?EnsemblGeneId )	
		} OPTIONAL {
		 ?s d2sgeneric:Mgd_id ?MouseGenomeDatabaseId.
		 BIND ( SUBSTR(?MouseGenomeDatabaseId,5) AS ?mgi_mainR )
		 BIND ( iri(concat("http://bio2rdf.org/mgi:", ?mgi_mainR)) AS ?mgi_main )	
		} OPTIONAL {
         	 ?s d2sgeneric:Pubmed_id ?PubmedIdsR .
		 BIND ( iri(concat("http://bio2rdf.org/pubmed:", ?PubmedIdsR)) AS ?PubmedIds )		
		} OPTIONAL {
         	 ?s d2sgeneric:Refseq_accession ?RefseqIdsR .
		 BIND ( iri(concat("http://bio2rdf.org/refseq:", ?RefseqIdsR)) AS ?RefseqIds )			
		} OPTIONAL {
         	 ?s d2sgeneric:Gene_family_id ?GeneFamilyTag .	
		} OPTIONAL {
         	 ?s d2sgeneric:Gene_family ?GeneFamilyDescription .	
		} OPTIONAL {
         	 ?s d2sgeneric:Ccds_id ?CcdsIdsR .
		 BIND ( iri(concat("http://bio2rdf.org/ccds:", ?CcdsIdsR)) AS ?CcdsIds )				
		} OPTIONAL {
         	 ?s d2sgeneric:Vega_id ?VegaIdsR .
		 BIND ( iri(concat("http://bio2rdf.org/vega:", ?VegaIdsR)) AS ?VegaIds )					
		} OPTIONAL {
         	 ?s d2sgeneric:Omim_id ?OmimIdSuppliedByNcbiR .
		 BIND ( iri(concat("http://bio2rdf.org/omim:", ?OmimIdSuppliedByNcbiR)) AS ?OmimIdSuppliedByNcbi )						
		} OPTIONAL {
         	 ?s d2sgeneric:Uniprot_ids ?UniprotIdSuppliedByUniprotR .
		 BIND ( iri(concat("http://bio2rdf.org/uniprot:", ?UniprotIdSuppliedByUniprotR)) AS ?UniprotIdSuppliedByUniprot )								
		} OPTIONAL {
         	 ?s d2sgeneric:Ucsc_id ?UcscIdSuppliedByUcscR .
		 BIND ( iri(concat("http://bio2rdf.org/ucsc:", ?UcscIdSuppliedByUcscR)) AS ?UcscIdSuppliedByUcsc )									
		} OPTIONAL {
         	 ?s d2sgeneric:Rgd_id ?RatGenomeDatabaseIdSuppliedByRgd .
		 BIND ( SUBSTR(?RatGenomeDatabaseIdSuppliedByRgd,5) AS ?rgdR )	
		 BIND ( iri(concat("http://bio2rdf.org/rgd:", ?rgdR)) AS ?rgd )	
		} OPTIONAL {
         	 ?s d2sgeneric:Rna_central_ids ?RnacentralIdsSuppliedByRnacentralR .
		 BIND ( iri(concat("http://bio2rdf.org/rnacentral:", ?RnacentralIdsSuppliedByRnacentralR)) AS ?RnacentralIdsSuppliedByRnacentral )		
		} OPTIONAL {
         	 ?s d2sgeneric:Lncipedia ?LncipediaSymbolSuppliedByLncipediaR .
		 BIND ( iri(concat("http://bio2rdf.org/lnci:", ?LncipediaSymbolSuppliedByLncipediaR)) AS ?LncipediaSymbolSuppliedByLncipedia )		
		}
		
		BIND ( iri(concat("http://bio2rdf.org/hgnc:", ?accessionID)) AS ?uri )
		
	}
}		

