PREFIX rr: <http://www.w3.org/ns/r2rml#> 
PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX dbo: <http://dbpedia.org/ontology/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rml: <http://semweb.mmlab.be/ns/rml#> 
PREFIX ql: <http://semweb.mmlab.be/ns/ql#> 
PREFIX d2rq: <http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#> 
PREFIX clinicaltrials_vocabulary: <http://bio2rdf.org/clinicaltrials_vocabulary:> 
PREFIX bio2rdf_vocabulary: <http://bio2rdf.org/bio2rdf_vocabulary:> 
PREFIX x2rm: <http://ids.unimaas.nl/xml2rdf/model#>

INSERT
{
	GRAPH <https://w3id.org/data2services/graph/clinicaltrials>{
		
		?uri	a clinicaltrials_vocabulary:Resource;
			rdf:type clinicaltrials_vocabulary:Measure;
			dc:identifier ?entId;
			rdfs:label ?label;
			dc:title ?measure_title;
			bio2rdf_vocabulary:namespace "clinicaltrials";
			bio2rdf_vocabulary:identifier ?id;
			bio2rdf_vocabulary:uri ?uri;

			clinicaltrials_vocabulary:title ?measure_title;
			clinicaltrials_vocabulary:units ?measure_units;
			clinicaltrials_vocabulary:param ?measure_param;
			clinicaltrials_vocabulary:dispersion ?measure_dispersion .
		
	}
}
WHERE {
    GRAPH <https://w3id.org/data2services/graph/xml2rdf> {

		?s x2rm:child:outcome_list ?outcome_list.

		?outcome_list x2rm:child:outcome ?outcome.
		
		?outcome  x2rm:child:measure_list ?measure_list.

		?measure_list  x2rm:child:measure ?measure.

		OPTIONAL{
			?measure  x2rm:child:title [
			  x2rm:hasValue ?measure_title
			].
		}OPTIONAL{
			?measure  x2rm:child:units [
			  x2rm:hasValue ?measure_units
			].
		}OPTIONAL{
			?measure  x2rm:child:param [
			  x2rm:hasValue ?measure_param
			].
		}OPTIONAL{
			?measure  x2rm:child:dispersion [
			  x2rm:hasValue ?measure_dispersion
			].
		}
		BIND (STRAFTER(str(?measure) , "http://ids.unimaas.nl/xml2rdf/data/") AS ?id)

		BIND (concat("clinicaltrials_resource:",?id) AS ?entId)

		BIND ( concat(?measure_title , " [clinicaltrials_resource:", ?id, "] ") AS ?label )
 
		BIND(iri(concat("http://bio2rdf.org/clinicaltrials_resource:",?id)) AS ?uri)	
		
	}
}		

