PREFIX rr: <http://www.w3.org/ns/r2rml#> 
PREFIX dc: <http://purl.org/dc/elements/1.1/> 
PREFIX dbo: <http://dbpedia.org/ontology/> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX rml: <http://semweb.mmlab.be/ns/rml#> 
PREFIX ql: <http://semweb.mmlab.be/ns/ql#> 
PREFIX d2rq: <http://www.wiwiss.fu-berlin.de/suhl/bizer/D2RQ/0.1#> 
PREFIX clinicaltrials_vocabulary: <http://bio2rdf.org/clinicaltrials_vocabulary:> 
PREFIX bio2rdf_vocabulary: <http://bio2rdf.org/bio2rdf_vocabulary:> 
PREFIX x2rm: <http://ids.unimaas.nl/xml2rdf/model#>

INSERT
{
	GRAPH <https://w3id.org/data2services/graph/clinicaltrials>{
		
		?uri	a clinicaltrials_vocabulary:Resource;
			rdf:type clinicaltrials_vocabulary:Secondary-Outcome;
			dc:identifier ?entId;
			rdfs:label ?label;
			dc:title ?title;
			bio2rdf_vocabulary:namespace "clinicaltrials";
			bio2rdf_vocabulary:identifier ?id;
			bio2rdf_vocabulary:uri ?uri;

			clinicaltrials_vocabulary:measure  ?measure;
			clinicaltrials_vocabulary:time-frame  ?time_frame;
			clinicaltrials_vocabulary:safety-issue  ?safety_issue;
			dc:description  ?description .
		
	}
}
WHERE {
    GRAPH <https://w3id.org/data2services/graph/xml2rdf> {
		
		?s rdf:type x2rm:clinical_study.

		?s x2rm:child:secondary_outcome ?secondary_outcome.

		?secondary_outcome  x2rm:child:measure [
			  x2rm:hasValue ?measure
		].

		?secondary_outcome  x2rm:child:time_frame [
			  x2rm:hasValue ?time_frame
		].

		?secondary_outcome  x2rm:child:saftey_issue [
			  x2rm:hasValue ?saftey_issue
		].

		?secondary_outcome  x2rm:child:description [
			  x2rm:hasValue ?description
		].
		
		BIND (STRAFTER(str(?secondary_outcome) , "http://ids.unimaas.nl/xml2rdf/data/") AS ?id)

		BIND (concat("clinicaltrials_resource:",?id) AS ?entId)

		BIND ( concat(?measure, " ", ?time_frame , " [clinicaltrials_resource:", ?id, "] ") AS ?label )

		BIND(iri(concat("http://bio2rdf.org/clinicaltrials_resource:",?id)) AS ?uri)	
		
	}
}		

